version: "3.9"

services:
  todo-list:
    build:
      context: .
      target: run
      args:
        - ARG_PORT=3030
        - ARG_ENABLE_METRICS=true
        - ARG_PROM_TOKEN=prom_token
    ports:
      - "80:3030"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./metrics/prom-config.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    depends_on:
      - todo-list

  grafana:
    image: grafana/grafana-enterprise:8.2.0
    ports:
      - 3000:3000
    volumes:
      - ./metrics/grafana-dashboard.json:/var/lib/grafana/dashboards/grafana-dashboard.json
      - ./metrics/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/grafana-dashboard.json"
    depends_on:
      - prometheus